version: "3.9"
services:
    mysql:
        image: mariadb:10.8.3
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        networks:
            - app-network

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - app-network

    mailpit:
        image: axllent/mailpit:latest
        restart: always
        ports:
            - 8025:8025  # Web UI for Mailpit
            - 1025:1025  # SMTP port for Mailpit
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
